### ISSUE TITLE
Затримки з оновленням

### ISSUE THREAD

**Issue by prozorro-support** [openprocurement/bi#1]
This Github issue is synchronized with Zendesk,

**Zendesk ticket ID:** [163](https://prozorro.zendesk.com/agent/#/tickets/163)
**Priority:** normal
**Zendesk assignee:** Служба підтримки/Мирослав

**Original ticket content:**

Станом на зараз 2015-07-27T08:45+0300 http://bi.prozorro.org не містить змін принаймні з п'ятниці, 2015-04-24.

**Comment by prozorro-support** [comment]
_Comment from Zendesk by myroslav@quintagroup.com at 2015-07-27 05:58:22 UTC:_

<div class="zd-comment"><p>Станом на зараз 2015-07-27T08:45+0300 <a href="http://bi.prozorro.org" rel="nofollow noreferrer" target="_blank">http://bi.prozorro.org</a> не містить змін принаймні з п&#39;ятниці, 2015-04-24.</p>
<p>Мирослав
<br />ЦБД та Аукціон</p></div>

**Comment by YaroslavKharchenko** [comment]
Была проблема с синхронизацией данных между серверами. Админы устранили ошибку. Сейчас данные актуальные.

**Comment by prozorro-support** [comment]
_Comment from Zendesk by myroslav@quintagroup.com at 2015-07-29 12:09:06 UTC:_

<div class="zd-comment"><p>Вітання,</p>
<p>Була проблема синхронізації даних між серверами. Її усунули. Постараємося знайти способи, щоб проблема не поверталася.</p>
<p>Мирослав
<br />ЦБД та Аукціон</p></div>

**Comment by myroslav** [comment]
Ярославе, вже кілька раз "залипала" синхронізація. В інших проектах такакого сорту проблеми, що час до часу повторюються на рівні адміністрування вирішуються регуларною автоматизованою перевіркою.

Можу зі своєї сторони запропонувати в автоматичному режимі (чи ззовні якимось HTTP запитом, чи зсередини, запуском якогось cmd скрипта на сервері) шукати тендери, які були "оголошені сьогодні". Тобто якщо до 12 год дня в будній день не з'явилося жодного нового тендера, то неполадки, і адміністратор мав би отримати повідомлення про потенційні проблеми.

Звичайно у вас імовірно є простіші способи подивитися, чи ще працює синхронізація. Поділіться думками з цього приводу.

**Comment by prozorro-support** [comment]
_Comment from Zendesk by myroslav@quintagroup.com at 2015-07-29 12:09:06 UTC:_

<div class="zd-comment"><p>Вітання,</p>
<p>Була проблема синхронізації даних між серверами. Її усунули. Постараємося знайти способи, щоб проблема не поверталася.</p>
<p>Мирослав
<br />ЦБД та Аукціон</p></div>

**Comment by YaroslavKharchenko** [comment]
Стандартные средства QlikSense сервера на данный момент не позволяют автоматизировать процесс контроля синхронизации. Нужно подумать о сторонних утилитах.

**Comment by prozorro-support** [comment]
_Comment from Zendesk by myroslav@quintagroup.com at 2015-07-29 12:09:06 UTC:_

<div class="zd-comment"><p>Вітання,</p>
<p>Була проблема синхронізації даних між серверами. Її усунули. Постараємося знайти способи, щоб проблема не поверталася.</p>
<p>Мирослав
<br />ЦБД та Аукціон</p></div>

**Comment by prozorro-support** [comment]
_Comment from Zendesk by myroslav@quintagroup.com at 2015-07-29 12:09:06 UTC:_

<div class="zd-comment"><p>Вітання,</p>
<p>Була проблема синхронізації даних між серверами. Її усунули. Постараємося знайти способи, щоб проблема не поверталася.</p>
<p>Мирослав
<br />ЦБД та Аукціон</p></div>
